#!/usr/local/munkireport/munkireport-python3
# Script by Bochoven and Tuxudo

import os, sys, plistlib, subprocess, platform, json, math, re

def run_sysctl_value(key):
    try:
        cmd = ['/usr/sbin/sysctl', '-n', key]
        proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        output, _ = proc.communicate()
        if proc.returncode != 0:
            return None
        value = output.decode("utf-8", errors="ignore").strip()
        return value if value else None
    except:
        return None

def get_perflevel_cluster_names():
    """Map hw.perflevel index to display cluster type."""
    perflevel_clusters = {}

    nperflevels = run_sysctl_value('hw.nperflevels')
    if not nperflevels:
        return perflevel_clusters

    try:
        perflevel_count = int(nperflevels)
    except:
        return perflevel_clusters

    for level_idx in range(perflevel_count):
        level_name = run_sysctl_value('hw.perflevel' + str(level_idx) + '.name')
        if not level_name:
            continue

        level_name_lc = level_name.lower()
        if 'super' in level_name_lc:
            perflevel_clusters[level_idx] = 'S-Cluster'
        elif 'perform' in level_name_lc:
            perflevel_clusters[level_idx] = 'P-Cluster'
        elif 'efficien' in level_name_lc:
            perflevel_clusters[level_idx] = 'E-Cluster'

    return perflevel_clusters

def normalize_cluster_name(raw_name, use_perflevel_index, perflevel_clusters):
    """Normalize powermetrics cluster names across Apple Silicon generations."""
    if not raw_name:
        return 'P-Cluster'

    prefix = raw_name[0].upper()
    idx_match = re.match(r'^[A-Za-z](\d+)', raw_name)

    # On newer Apple Silicon, resolve ambiguous P*/M* naming by perflevel.
    if use_perflevel_index and idx_match:
        try:
            perf_idx = int(idx_match.group(1))
            if perf_idx in perflevel_clusters:
                return perflevel_clusters[perf_idx]
        except:
            pass

    if prefix == 'E':
        return 'E-Cluster'

    if prefix == 'S':
        return 'S-Cluster'

    # M* clusters are treated as middle/performance cores.
    if prefix == 'M':
        return 'P-Cluster'

    # Default: P* and unknown prefixes are treated as performance.
    return 'P-Cluster'

def get_usage_metrics():
    cmd = ['/usr/bin/powermetrics', '--show-initial-usage', ' -s', 'network,disk', '-f', 'plist', '-n', '0']

    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = proc.communicate()

    # Need to remove a broken key "<key>all_tasks</key>" that Python doesn't like
    output = output.decode().replace("&","and")

    # Manually build out the plist because the command spews garbage
    plist_build = '<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"><plist version="1.0"><dict>'
    for idx, line in enumerate(output.split("\n")):
        if "opackets" in line or "opacket_rate" in line or "ipackets" in line or "ipacket_rate" in line or "obytes" in line or "obyte_rate" in line or "ibytes" in line or "ibyte_rate" in line or "rops_diff" in line or "rops_per_s" in line or "wops_diff" in line or "wops_per_s" in line or "rbytes_diff" in line or "rbytes_per_s" in line or "wbytes_diff" in line or "wbytes_per_s" in line:
            plist_build = plist_build + line

    plist_build = plist_build + '</dict></plist>'

    try:

        plist = plistlib.loads(plist_build.encode())
    except:
        plist = {}

    cmd = ['/usr/bin/powermetrics', '-s', 'cpu_power,gpu_power,thermal,battery', '-n', '1', '-i', '1000', '-f', 'plist']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = proc.communicate()

    try:

        plist.update(plistlib.loads(output.decode().rstrip(' \t\r\n\0').replace("&","and").encode()))
    except:
        pass

    return plist

def parse_usage_plist(plist):
    usage_info = {}

    for item in plist:
        if item == 'timestamp':
            try:
                usage_info['timestamp'] = plist[item]
            except:
                pass
        elif item == 'thermal_pressure':
            try:
                usage_info['thermal_pressure'] = plist[item]
            except:
                pass
        elif item == 'backlight': # Intel Macs
            try:
                usage_info['backlight_max'] = plist[item]['max']
            except:
                pass
            try:
                usage_info['backlight_min'] = plist[item]['min']
            except:
                pass
            try:
                usage_info['backlight'] = plist[item]['value']
            except:
                pass
        elif item == 'keyboard_backlight': # Intel Macs
            try:
                usage_info['keyboard_backlight'] = plist[item]['value']
            except:
                pass

        elif item == 'ibyte_rate':
            usage_info['ibyte_rate'] = plist[item]
        elif item == 'ibytes':
            usage_info['ibytes'] = plist[item]
        elif item == 'ipacket_rate':
            usage_info['ipacket_rate'] = plist[item]
        elif item == 'ipackets':
            usage_info['ipackets'] = plist[item]
        elif item == 'obyte_rate':
            usage_info['obyte_rate'] = plist[item]
        elif item == 'obytes':
            usage_info['obytes'] = plist[item]
        elif item == 'opacket_rate':
            usage_info['opacket_rate'] = plist[item]
        elif item == 'opackets':
            usage_info['opackets'] = plist[item]

        elif item == 'rbytes_per_s':
            usage_info['rbytes_per_s'] = plist[item]
        elif item == 'rops_per_s':
            usage_info['rops_per_s'] = plist[item]
        elif item == 'wbytes_per_s':
            usage_info['wbytes_per_s'] = plist[item]
        elif item == 'wops_per_s':
            usage_info['wops_per_s'] = plist[item]
        elif item == 'rbytes_diff':
            usage_info['rbytes_diff'] = plist[item]
        elif item == 'rops_diff':
            usage_info['rops_diff'] = plist[item]
        elif item == 'wbytes_diff':
            usage_info['wbytes_diff'] = plist[item]
        elif item == 'wops_diff':
            usage_info['wops_diff'] = plist[item]

        elif item == 'processor':
            try: # Intel Macs
                usage_info['package_watts'] = plist[item]['package_watts']
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['package_watts'] = (plist[item]['combined_power']/1000)
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['cpu_watts'] = (plist[item]['cpu_energy']/1000)
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['gpu_watts'] = (plist[item]['gpu_energy']/1000)
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['clusters'] = json.dumps(process_clusters(plist[item]['clusters']))
            except:
                pass
            try:
                usage_info['package_joules'] = plist[item]['package_joules']
            except:
                pass
            try:
                usage_info['freq_hz'] = plist[item]['freq_hz']
            except:
                pass
            try:
                usage_info['freq_ratio'] = plist[item]['freq_ratio']
            except:
                pass
        elif item == 'GPU': # Intel Macs
            try:
                usage_info['gpu_name'] = plist[item][0]['name'].replace("IntelIG", "Intel iGPU")
            except:
                pass
            try:
                usage_info['gpu_freq_hz'] = plist[item][0]['freq_hz']
            except:
                pass
            try:
                usage_info['gpu_freq_mhz'] = plist[item][0]['freq_mhz']
            except:
                pass
            try:
                usage_info['gpu_freq_ratio'] = plist[item][0]['freq_ratio']
            except:
                pass
            try:
                usage_info['gpu_busy'] = plist[item][0]['misc_counters']['GPU Busy']
            except:
                pass
        elif item == 'gpu': # Apple Silicon Macs
            try:
                usage_info['gpu_freq_hz'] = int(plist[item]['freq_hz']*1000000) # This value is in Mhz on AS
                usage_info['gpu_freq_mhz'] = int(plist[item]['freq_hz']) # This value is in Mhz on AS
                usage_info['gpu_busy'] = (1-plist[item]['idle_ratio'])
            except:
                pass
        elif item == 'kern_bootargs':
            try:
                usage_info['kern_bootargs'] = plist[item]
            except:
                pass
    return usage_info

def get_as_backlight():
    # Gets the backlight info for Apple Silicon Macs
    cmd = ['/usr/libexec/corebrightnessdiag', 'status-info']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, unused_error) = proc.communicate()

    # The output is sometimes split
    if b"Unable to dump a property list." in output:
      output=output.decode("utf-8", errors="ignore").split("Unable to dump a property list.")[0].encode()

    try:

        plist = plistlib.loads(output)
    except Exception:
        return {}

    result = {}

    try:
        # Because there can be multiple displays, we need to find the primary display
        if plist["CBDisplayInfo"] and plist["CBDisplayInfo"][0] and plist["CBDisplayInfo"][0]["CBDisplayInfoDeviceID"]:
            main_display=plist["CBDisplayInfo"][0]["CBDisplayInfoDeviceID"]

            if plist["CBDisplays"]:
                for display in plist["CBDisplays"]:
                    # Look for the primary display by device ID
                    if plist["CBDisplays"][display]["Display"] and plist["CBDisplays"][display]["Display"]["CBDisplayInfo"] and plist["CBDisplays"][display]["Display"]["CBDisplayInfo"]["CBDisplayInfoDeviceID"] and plist["CBDisplays"][display]["Display"]["CBDisplayInfo"]["CBDisplayInfoDeviceID"] == main_display:

                        backlight_max = plist["CBDisplays"][display]["Display"]["BrightnessLimit"]
                        backlight = int(plist["CBDisplays"][display]["Display"]["NitsPhysical"])

                        result.update({'backlight_max': backlight_max})
                        result.update({'backlight_min': "0"})
                        result.update({'backlight': backlight})

                        # We found the display we're looking for
                        break
    except:
        pass

    try:
        if plist['CBKeyboards']:
            for keyboard in plist['CBKeyboards']:
                if plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"] and plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"] and (plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"]["KeyboardBacklightBrightness"] or plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"]["KeyboardBacklightBrightness"] == 0):
                    
                    keyboard_backlight = int(plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"]["KeyboardBacklightBrightness"] * 100)
                    result.update({'keyboard_backlight': keyboard_backlight})
    except:
        pass

    return result

def process_clusters(cpu_clusters):
    # Lovely lifted from https://github.com/tlkh/asitop

    cpu_metric_dict = {}
    perflevel_clusters = get_perflevel_cluster_names()

    # Verified patterns:
    # - M1/M3 era: explicit E/S tier prefixes may coexist with P0/P1 cluster names.
    # - M5 variants: sometimes only P0/P1 are present, where perflevel names disambiguate.
    # Therefore, use perflevel index mapping only when names are ambiguous-only
    # (P/M with numeric suffixes and no explicit E/S tier prefixes in the sample).
    prefixes = []
    has_numeric_suffix = False
    for cluster in cpu_clusters:
        cluster_name = cluster.get("name", "")
        if not cluster_name:
            continue
        prefixes.append(cluster_name[0].upper())
        if re.match(r'^[A-Za-z]\d+', cluster_name):
            has_numeric_suffix = True

    has_explicit_tier_prefixes = any(prefix in ('E', 'S') for prefix in prefixes)
    has_only_ambiguous_prefixes = len(prefixes) > 0 and all(prefix in ('P', 'M') for prefix in prefixes)
    use_perflevel_index = bool(perflevel_clusters) and (not has_explicit_tier_prefixes) and has_only_ambiguous_prefixes and has_numeric_suffix

    for cluster in cpu_clusters:
        normalized_name = normalize_cluster_name(
            cluster.get("name", ""),
            use_perflevel_index,
            perflevel_clusters
        )
        # cpu_metric_dict[name+"_freq_Mhz"] = int(cluster["freq_hz"]/(1e6))
        # cpu_metric_dict[name+"_active"] = int((1 - cluster["idle_ratio"])*100)
        for cpu in cluster["cpus"]:
            cpu_metric_dict[normalized_name + str(cpu["cpu"]) + "_freq_Mhz"] = int(cpu["freq_hz"] / (1e6))
            cpu_metric_dict[normalized_name + str(cpu["cpu"]) + "_active"] = int((1 - cpu["idle_ratio"]) * 100)
    
    # cpu_metric_dict["e_core"] = e_core
    # cpu_metric_dict["p_core"] = p_core
    # if "E-Cluster_active" not in cpu_metric_dict:
    #     # M1 Ultra
    #     cpu_metric_dict["E-Cluster_active"] = int((cpu_metric_dict["E0-Cluster_active"] + cpu_metric_dict["E1-Cluster_active"])/2)
    # if "E-Cluster_freq_Mhz" not in cpu_metric_dict:
    #     # M1 Ultra
    #     cpu_metric_dict["E-Cluster_freq_Mhz"] = max(cpu_metric_dict["E0-Cluster_freq_Mhz"], cpu_metric_dict["E1-Cluster_freq_Mhz"])
    # if "P-Cluster_active" not in cpu_metric_dict:
    #     if "P2-Cluster_active" in cpu_metric_dict:
    #         # M1 Ultra
    #         cpu_metric_dict["P-Cluster_active"] = int((cpu_metric_dict["P0-Cluster_active"] + cpu_metric_dict["P1-Cluster_active"] +
    #                                                   cpu_metric_dict["P2-Cluster_active"] + cpu_metric_dict["P3-Cluster_active"]) / 4)
    #     else:
    #         cpu_metric_dict["P-Cluster_active"] = int((cpu_metric_dict["P0-Cluster_active"] + cpu_metric_dict["P1-Cluster_active"])/2)
    # if "P-Cluster_freq_Mhz" not in cpu_metric_dict:
    #     if "P2-Cluster_freq_Mhz" in cpu_metric_dict:
    #         # M1 Ultra
    #         freqs = [
    #             cpu_metric_dict["P0-Cluster_freq_Mhz"],
    #             cpu_metric_dict["P1-Cluster_freq_Mhz"],
    #             cpu_metric_dict["P2-Cluster_freq_Mhz"],
    #             cpu_metric_dict["P3-Cluster_freq_Mhz"]]
    #         cpu_metric_dict["P-Cluster_freq_Mhz"] = max(freqs)
    #     else:
    #         cpu_metric_dict["P-Cluster_freq_Mhz"] = max(cpu_metric_dict["P0-Cluster_freq_Mhz"], cpu_metric_dict["P1-Cluster_freq_Mhz"])

    return cpu_metric_dict

def get_processes():

    cmd = ['/bin/ps', '-eo', 'pid,pcpu,pmem,user,rss,comm']

    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = proc.communicate()

    arr = []
    for line in output.decode("utf-8", errors="ignore").split('\n'):

        # Don't process the header
        if "%CPU" in line:
            continue

        # Split at space
        fields = line.split(" ")

        # Break at the blank/empty row
        if len(fields) < 2:
            break

        # Remove empty columns
        fields = [i for a,i in enumerate(fields) if i!='']

        # Minimize CPU and memory usage percent
        if fields[1] == "0.0":
            fields[1] = "0"        
        if fields[2] == "0.0":
            fields[2] = "0"

        # Process memory usage
        memory_k = int(fields[4])
        if memory_k > 100:
            size_name = ("KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
            i = int(math.floor(math.log(memory_k, 1024)))
            p = math.pow(1024, i)
            s = round(memory_k / p, 2)
            fields[4] = "%s %s" % (s, size_name[i])
        else:
            fields[4] = ""

        # Rejoin process path
        if len(fields) > 6:
            while len(fields) > 6:
                fields[5] = fields[5] + " " + fields[6]
                fields.remove(fields[6])

            fields[5] = fields[5].strip()

        # Get the process name from process path
        fields.append(fields[5].split("/")[-1])

        # Build the entry 
        arr.append({
            "pid": fields[0],
            "cpu": fields[1],
            "memp": fields[2],
            "usr": fields[3],
            "mem": fields[4],
            "proc": fields[6],
            "path": fields[5],
        })

    return json.dumps(arr)

def get_cpu_usage():
    cmd = ['/usr/bin/top', '-l', '1', '-stats', 'pid']

    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = proc.communicate()

    out = {}

    for line in output.decode("utf-8", errors="ignore").split('\n'):

        if "Load Avg:" in line:
            out["load_avg"] = re.sub('Load Avg: ', '', line).strip()
        elif "CPU usage: " in line:
            cpu_usage = re.sub('CPU usage: ', '', line).split(', ')
            out["cpu_user"] = re.sub(' user', '', cpu_usage[0]).strip()
            out["cpu_sys"] = re.sub(' sys', '', cpu_usage[1]).strip()
            out["cpu_idle"] = re.sub(' idle ', '', cpu_usage[2]).strip()
    return out

def getDarwinVersion():
    """Returns the Darwin version."""
    # Catalina -> 10.15.7 -> 19.6.0 -> 19
    darwin_version_tuple = platform.release().split('.')
    return int(darwin_version_tuple[0]) 

def main():
    """Main"""

    # If less than macOS 10.10 (Darwin) 14, skip and write empty file
    if getDarwinVersion() < 14:
        result = dict()

    else :
        # Get results
        result = dict()
        info = get_usage_metrics()
        result = parse_usage_plist(info)
        result.update({'processes': get_processes()})
        result.update(get_cpu_usage())

        # Check if Apple Silicon Mac
        if "arm" in os.uname()[3].lower():
            result.update(get_as_backlight())

    # Write results to cache

    cachedir = '%s/cache' % os.path.dirname(os.path.realpath(__file__))
    output_plist = os.path.join(cachedir, 'usage_stats.plist')
    with open(output_plist, 'wb') as fp:
        plistlib.dump(result, fp, fmt=plistlib.FMT_XML)

if __name__ == "__main__":
    main()
