#!/usr/local/munkireport/munkireport-python3
# Script by Bochoven and Tuxudo

import os, sys, plistlib, subprocess, platform, json

def get_usage_metrics():
    cmd = ['/usr/bin/powermetrics', '--show-initial-usage', ' -s', "network,disk", '-f', 'plist', '-n', '0']

    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = proc.communicate()

    # Need to remove a broken key "<key>all_tasks</key>" that Python doesn't like
    output = output.decode().replace("<key>all_tasks</key>","")

    try:
        plist = plistlib.readPlistFromString(output.rstrip(' \t\r\n\0').strip())
    except AttributeError as e:
        try:
            plist = plistlib.loads(output.rstrip(' \t\r\n\0').encode())
        except:
            plist = {}

    cmd = ['/usr/bin/powermetrics', '-s', 'cpu_power,gpu_power,thermal,battery', '-n', '1', '-f', 'plist']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1,
                        stdin=subprocess.PIPE,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    output, err = proc.communicate()

    try:
        plist.update(plistlib.readPlistFromString(output.rstrip(' \t\r\n\0')))
    except AttributeError as e:
        plist.update(plistlib.loads(output.decode().rstrip(' \t\r\n\0').encode()))

    return plist

def parse_usage_plist(plist):
    usage_info = {}
    for item in plist:
        if item == 'timestamp':
            try:
                usage_info['timestamp'] = plist[item]
            except:
                pass
        elif item == 'thermal_pressure':
            try:
                usage_info['thermal_pressure'] = plist[item]
            except:
                pass
        elif item == 'backlight': # Intel Macs
            try:
                usage_info['backlight_max'] = plist[item]['max']
            except:
                pass
            try:
                usage_info['backlight_min'] = plist[item]['min']
            except:
                pass
            try:
                usage_info['backlight'] = plist[item]['value']
            except:
                pass
        elif item == 'keyboard_backlight': # Intel Macs
            try:
                usage_info['keyboard_backlight'] = plist[item]['value']
            except:
                pass
        elif item == 'network':
            try:
                usage_info['ibyte_rate'] = plist[item]['ibyte_rate']
            except:
                pass
            try:
                usage_info['ibytes'] = plist[item]['ibytes']
            except:
                pass
            try:
                usage_info['ipacket_rate'] = plist[item]['ipacket_rate']
            except:
                pass
            try:
                usage_info['ipackets'] = plist[item]['ipackets']
            except:
                pass
            try:
                usage_info['obyte_rate'] = plist[item]['obyte_rate']
            except:
                pass
            try:
                usage_info['obytes'] = plist[item]['obytes']
            except:
                pass
            try:
                usage_info['opacket_rate'] = plist[item]['opacket_rate']
            except:
                pass
            try:
                usage_info['opackets'] = plist[item]['opackets']
            except:
                pass
        elif item == 'disk':
            try:
                usage_info['rbytes_per_s'] = plist[item]['rbytes_per_s']
            except:
                pass
            try: 
                usage_info['rops_per_s'] = plist[item]['rops_per_s']
            except:
                pass
            try:
                usage_info['wbytes_per_s'] = plist[item]['wbytes_per_s']
            except:
                pass
            try:
                usage_info['wops_per_s'] = plist[item]['wops_per_s']
            except:
                pass
            try:
                usage_info['rbytes_diff'] = plist[item]['rbytes_diff']
            except:
                pass
            try:
                usage_info['rops_diff'] = plist[item]['rops_diff']
            except:
                pass
            try:
                usage_info['wbytes_diff'] = plist[item]['wbytes_diff']
            except:
                pass
            try:
                usage_info['wops_diff'] = plist[item]['wops_diff']
            except:
                pass
        elif item == 'processor':
            try: # Intel Macs
                usage_info['package_watts'] = plist[item]['package_watts']
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['package_watts'] = (plist[item]['combined_power']/1000)
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['cpu_watts'] = (plist[item]['cpu_energy']/1000)
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['gpu_watts'] = (plist[item]['gpu_energy']/1000)
            except:
                pass
            try: # Apple Silicon Macs
                usage_info['clusters'] = json.dumps(process_clusters(plist[item]['clusters']))
            except:
                pass
            try:
                usage_info['package_joules'] = plist[item]['package_joules']
            except:
                pass
            try:
                usage_info['freq_hz'] = plist[item]['freq_hz']
            except:
                pass
            try:
                usage_info['freq_ratio'] = plist[item]['freq_ratio']
            except:
                pass
        elif item == 'GPU': # Intel Macs
            try:
                usage_info['gpu_name'] = plist[item][0]['name'].replace("IntelIG", "Intel iGPU")
            except:
                pass
            try:
                usage_info['gpu_freq_hz'] = plist[item][0]['freq_hz']
            except:
                pass
            try:
                usage_info['gpu_freq_mhz'] = plist[item][0]['freq_mhz']
            except:
                pass
            try:
                usage_info['gpu_freq_ratio'] = plist[item][0]['freq_ratio']
            except:
                pass
            try:
                usage_info['gpu_busy'] = plist[item][0]['misc_counters']['GPU Busy']
            except:
                pass
        elif item == 'gpu': # Apple Silicon Macs
            try:
                usage_info['gpu_freq_hz'] = int(plist[item]['freq_hz']*1000000) # This value is in Mhz on AS
                usage_info['gpu_freq_mhz'] = int(plist[item]['freq_hz']) # This value is in Mhz on AS
                usage_info['gpu_busy'] = (1-plist[item]['idle_ratio'])
            except:
                pass
        elif item == 'kern_bootargs':
            try:
                usage_info['kern_bootargs'] = plist[item]
            except:
                pass
    return usage_info

def get_as_backlight():
    # Gets the backlight info for Apple Silicon Macs
    cmd = ['/usr/libexec/corebrightnessdiag', 'status-info']
    proc = subprocess.Popen(cmd, shell=False, bufsize=-1, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (output, unused_error) = proc.communicate()

    # The output is sometimes split
    if b"Unable to dump a property list." in output:
      output=output.decode("utf-8", errors="ignore").split("Unable to dump a property list.")[0].encode()

    try:
        plist = plistlib.readPlistFromString(output)
    except AttributeError as e:
        plist = plistlib.loads(output)

    result = {}

    try:
        # Because there can be multiple displays, we need to find the primary display
        if plist["CBDisplayInfo"] and plist["CBDisplayInfo"][0] and plist["CBDisplayInfo"][0]["CBDisplayInfoDeviceID"]:
            main_display=plist["CBDisplayInfo"][0]["CBDisplayInfoDeviceID"]

            if plist["CBDisplays"]:
                for display in plist["CBDisplays"]:
                    # Look for the primary display by device ID
                    if plist["CBDisplays"][display]["Display"] and plist["CBDisplays"][display]["Display"]["CBDisplayInfo"] and plist["CBDisplays"][display]["Display"]["CBDisplayInfo"]["CBDisplayInfoDeviceID"] and plist["CBDisplays"][display]["Display"]["CBDisplayInfo"]["CBDisplayInfoDeviceID"] == main_display:

                        backlight_max = plist["CBDisplays"][display]["Display"]["BrightnessLimit"]
                        backlight = int(plist["CBDisplays"][display]["Display"]["NitsPhysical"])

                        result.update({'backlight_max': backlight_max})
                        result.update({'backlight_min': "0"})
                        result.update({'backlight': backlight})

                        # We found the display we're looking for
                        break
    except:
        pass

    try:
        if plist['CBKeyboards']:
            for keyboard in plist['CBKeyboards']:
                if plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"] and plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"] and (plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"]["KeyboardBacklightBrightness"] or plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"]["KeyboardBacklightBrightness"] == 0):
                    
                    keyboard_backlight = int(plist['CBKeyboards'][keyboard]["CBKeyboardBacklightContainer"]["KeyboardBacklightBrightness"] * 100)
                    result.update({'keyboard_backlight': keyboard_backlight})
    except:
        pass

    return result

def process_clusters(cpu_clusters):
    # Lovely lifted from https://github.com/tlkh/asitop

    e_core = []
    p_core = []
    cpu_metric_dict = {}

    for cluster in cpu_clusters:
        name = cluster["name"]
        # cpu_metric_dict[name+"_freq_Mhz"] = int(cluster["freq_hz"]/(1e6))
        # cpu_metric_dict[name+"_active"] = int((1 - cluster["idle_ratio"])*100)
        for cpu in cluster["cpus"]:
            name = 'E-Cluster' if name[0] == 'E' else 'P-Cluster'
            core = e_core if name[0] == 'E' else p_core
            core.append(cpu["cpu"])
            cpu_metric_dict[name + str(cpu["cpu"]) + "_freq_Mhz"] = int(cpu["freq_hz"] / (1e6))
            cpu_metric_dict[name + str(cpu["cpu"]) + "_active"] = int((1 - cpu["idle_ratio"]) * 100)
    
    # cpu_metric_dict["e_core"] = e_core
    # cpu_metric_dict["p_core"] = p_core
    # if "E-Cluster_active" not in cpu_metric_dict:
    #     # M1 Ultra
    #     cpu_metric_dict["E-Cluster_active"] = int((cpu_metric_dict["E0-Cluster_active"] + cpu_metric_dict["E1-Cluster_active"])/2)
    # if "E-Cluster_freq_Mhz" not in cpu_metric_dict:
    #     # M1 Ultra
    #     cpu_metric_dict["E-Cluster_freq_Mhz"] = max(cpu_metric_dict["E0-Cluster_freq_Mhz"], cpu_metric_dict["E1-Cluster_freq_Mhz"])
    # if "P-Cluster_active" not in cpu_metric_dict:
    #     if "P2-Cluster_active" in cpu_metric_dict:
    #         # M1 Ultra
    #         cpu_metric_dict["P-Cluster_active"] = int((cpu_metric_dict["P0-Cluster_active"] + cpu_metric_dict["P1-Cluster_active"] +
    #                                                   cpu_metric_dict["P2-Cluster_active"] + cpu_metric_dict["P3-Cluster_active"]) / 4)
    #     else:
    #         cpu_metric_dict["P-Cluster_active"] = int((cpu_metric_dict["P0-Cluster_active"] + cpu_metric_dict["P1-Cluster_active"])/2)
    # if "P-Cluster_freq_Mhz" not in cpu_metric_dict:
    #     if "P2-Cluster_freq_Mhz" in cpu_metric_dict:
    #         # M1 Ultra
    #         freqs = [
    #             cpu_metric_dict["P0-Cluster_freq_Mhz"],
    #             cpu_metric_dict["P1-Cluster_freq_Mhz"],
    #             cpu_metric_dict["P2-Cluster_freq_Mhz"],
    #             cpu_metric_dict["P3-Cluster_freq_Mhz"]]
    #         cpu_metric_dict["P-Cluster_freq_Mhz"] = max(freqs)
    #     else:
    #         cpu_metric_dict["P-Cluster_freq_Mhz"] = max(cpu_metric_dict["P0-Cluster_freq_Mhz"], cpu_metric_dict["P1-Cluster_freq_Mhz"])

    return cpu_metric_dict

def getDarwinVersion():
    """Returns the Darwin version."""
    # Catalina -> 10.15.7 -> 19.6.0 -> 19
    darwin_version_tuple = platform.release().split('.')
    return int(darwin_version_tuple[0]) 

def main():
    """Main"""

    # If less than macOS 10.10 (Darwin) 14, skip and write empty file
    if getDarwinVersion() < 14:
        result = dict()

    else :
        # Get results
        result = dict()
        info = get_usage_metrics()
        result = parse_usage_plist(info)

        # Check if Apple Silicon Mac
        if "arm" in os.uname()[3].lower():
            result.update(get_as_backlight())

    # Write results to cache
    cachedir = '%s/cache' % os.path.dirname(os.path.realpath(__file__))
    output_plist = os.path.join(cachedir, 'usage_stats.plist')
    try:
        plistlib.writePlist(result, output_plist)
    except:
        with open(output_plist, 'wb') as fp:
            plistlib.dump(result, fp, fmt=plistlib.FMT_XML)

if __name__ == "__main__":
    main()
